apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- web.yaml
- landing.yaml
- api.yaml
- catalog.yaml
- postgres.yaml
- redis.yaml
- backup.yaml
- ingress.yaml

configMapGenerator:
- name: landing-html
  namespace: shop
  files:
  - index.html=landing/index.html
- name: landing-conf
  namespace: shop
  files:
  - default.conf=landing/default.conf
